// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QCO.Models;

#nullable disable

namespace QCO.Migrations
{
    [DbContext(typeof(QCOContext))]
    [Migration("20250227035157_AddUsridToLayoutMonitoringSheet")]
    partial class AddUsridToLayoutMonitoringSheet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("QCO.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("QCO.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("QCO.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("QCO.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("QCO.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("QCO.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("QCO.Models.TblCauseLookup", b =>
                {
                    b.Property<int>("CAUSEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CAUSEID"));

                    b.Property<string>("CAUSE_OF_DELAY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CAUSEID");

                    b.ToTable("tbl_Cause_Lookups");
                });

            modelBuilder.Entity("QCO.Models.TblLayoutMonitoringSheet", b =>
                {
                    b.Property<int>("Slno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SLNO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Slno"));

                    b.Property<string>("BookingNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BOOKING_NO");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BUYER_NAME");

                    b.Property<DateTime?>("FeedFinish")
                        .HasColumnType("datetime")
                        .HasColumnName("FEED_FINISH");

                    b.Property<DateTime?>("FeedStart")
                        .HasColumnType("datetime")
                        .HasColumnName("FEED_START");

                    b.Property<string>("LineNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LINE_NO");

                    b.Property<DateTime?>("MonitoringDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MONITORING_DATE");

                    b.Property<DateTime?>("PreStyleFinish")
                        .HasColumnType("datetime")
                        .HasColumnName("PRE_STYLE_FINISH");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<double?>("Total_SMV")
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_SMV");

                    b.HasKey("Slno");

                    b.ToTable("tbl_LayoutMonitoringSheet", (string)null);
                });

            modelBuilder.Entity("QCO.Models.TblLayoutMonitoringSheetD", b =>
                {
                    b.Property<int>("Trnsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRNSID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trnsid"));

                    b.Property<decimal?>("McSetupDuration")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("MC_SETUP_DURATION");

                    b.Property<TimeOnly?>("McSetupFinish")
                        .HasColumnType("time")
                        .HasColumnName("MC_SETUP_FINISH");

                    b.Property<TimeOnly?>("McSetupStart")
                        .HasColumnType("time")
                        .HasColumnName("MC_SETUP_START");

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROCESS_NAME");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RESOURCE_NAME");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int")
                        .HasColumnName("SEQUENCE_NO");

                    b.Property<int?>("Slno")
                        .HasColumnType("int")
                        .HasColumnName("SLNO");

                    b.HasKey("Trnsid");

                    b.HasIndex("Slno");

                    b.ToTable("tbl_LayoutMonitoringSheet_D", (string)null);
                });

            modelBuilder.Entity("QCO.Models.tbl_Cause_Detail", b =>
                {
                    b.Property<int>("DID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DID"));

                    b.Property<int?>("CAUSEID")
                        .HasColumnType("int");

                    b.Property<string>("REMARKS")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("TIME")
                        .HasColumnType("int");

                    b.Property<int?>("TRNSID")
                        .HasColumnType("int")
                        .HasColumnName("TRNSID");

                    b.HasKey("DID");

                    b.HasIndex("TRNSID");

                    b.ToTable("tbl_Cause_Details", (string)null);
                });

            modelBuilder.Entity("QCO.Models.tbl_Cause_Of_Delay", b =>
                {
                    b.Property<int>("CAUSEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CAUSEID"));

                    b.Property<string>("CAUSE_OF_DELAY")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("REMARKS")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CAUSEID");

                    b.ToTable("tbl_Cause_Of_Delay", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("QCO.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QCO.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QCO.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("QCO.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QCO.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("QCO.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QCO.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("QCO.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QCO.Models.AspNetUserToken", b =>
                {
                    b.HasOne("QCO.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QCO.Models.TblLayoutMonitoringSheetD", b =>
                {
                    b.HasOne("QCO.Models.TblLayoutMonitoringSheet", "LayoutMonitoringSheet")
                        .WithMany("DetailRecords")
                        .HasForeignKey("Slno")
                        .HasConstraintName("FK_TblLayoutMonitoringSheet_Slno");

                    b.Navigation("LayoutMonitoringSheet");
                });

            modelBuilder.Entity("QCO.Models.tbl_Cause_Detail", b =>
                {
                    b.HasOne("QCO.Models.TblLayoutMonitoringSheetD", null)
                        .WithMany("SavedCauses")
                        .HasForeignKey("TRNSID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QCO.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("QCO.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("QCO.Models.TblLayoutMonitoringSheet", b =>
                {
                    b.Navigation("DetailRecords");
                });

            modelBuilder.Entity("QCO.Models.TblLayoutMonitoringSheetD", b =>
                {
                    b.Navigation("SavedCauses");
                });
#pragma warning restore 612, 618
        }
    }
}
